import pygame
from Constants.sizes import *

pygame.init()

# Шрифт
FONT = pygame.font.Font(None, 46)

# NEW DATA AND MC TAB
PUMPING_INFO_RECT = pygame.Rect(PUMPING_LIST_POSITION, LISTS_START_Y_OFFSET + LISTS_HEIGHT + LISTS_OFFSET,
                                LISTS_WIDTH*3 + LISTS_OFFSET*2, 250)
SELECT_PUMPING_RECT = pygame.Rect(PUMPING_LIST_POSITION, 80, LISTS_WIDTH, TEXT_HIGH)

SELECT_SIGNAL_RECT = pygame.Rect(MODELING_LIST_POSITION, 80, LISTS_WIDTH, TEXT_HIGH)
SELECT_BACKGROUND_RECT = pygame.Rect(MODELING_LIST_POSITION, LISTS_HEIGHT//2 + LISTS_START_Y_OFFSET,
                                     LISTS_WIDTH, TEXT_HIGH)

SELECT_NTUPLE_VARS_RECT = pygame.Rect(NTIPLE_VARS_LIST_POSITION, 80, LISTS_WIDTH, TEXT_HIGH)


# EXISTING DATA AND MC TAB

EXISTING_DATA_INPUT_TEXT_RECT = pygame.Rect(WIDTH // 2 - 2 * LISTS_WIDTH, 80, 4 * LISTS_WIDTH, 200)

# SELECTIONS TAB
SELECT_TO_DRAW_RECT = pygame.Rect(PUMPING_LIST_POSITION, 80, LISTS_WIDTH, TEXT_HIGH)
BEAM_POINTS_RECT = pygame.Rect(PUMPING_LIST_POSITION, PUMPING_INFO_RECT.top - LISTS_OFFSET, LISTS_WIDTH, TEXT_HIGH)
HIST_RECT = pygame.Rect(MODELING_LIST_POSITION, 150, 2 * LISTS_WIDTH + LISTS_OFFSET, LISTS_HEIGHT)
INPUT_LIMITS_RECT = pygame.Rect(MODELING_LIST_POSITION, PUMPING_INFO_RECT.top - LISTS_OFFSET, LISTS_WIDTH, TEXT_HIGH)
INPUT_SELECTION_CONDITIONS_RECT = pygame.Rect(MODELING_LIST_POSITION,
                                              INPUT_LIMITS_RECT.y + 2*TEXT_HIGH + TEXT_OFFSET_INSIDE_LIST,
                                              LISTS_WIDTH, TEXT_HIGH)


# TMVA TAB
SELCTED_PARAMS_RECT = SELECT_PUMPING_RECT
BACKGROUNDS_LIST_RECT = SELECT_SIGNAL_RECT
TMVA_HIST_RECT = pygame.Rect(MODELING_LIST_POSITION, 150, 2 * LISTS_WIDTH + LISTS_OFFSET, LISTS_HEIGHT)
DISCRIMINATORS_RECT = SELECT_NTUPLE_VARS_RECT
SELECTIONS_SIGNAL_INPUT = pygame.Rect(PUMPING_LIST_POSITION, PUMPING_INFO_RECT.top, LISTS_WIDTH, TEXT_HIGH)
SELECTIONS_BACKGR_INPUT = pygame.Rect(PUMPING_LIST_POSITION,
                                              SELECTIONS_SIGNAL_INPUT.y + 2*TEXT_HIGH + TEXT_OFFSET_INSIDE_LIST,
                                              LISTS_WIDTH, TEXT_HIGH)

# TMVA results
SELECT_BKG_RECT = pygame.Rect(LISTS_START_X_OFFSET, 80,
                                          2*BUTTON_WIDTH + SPACING, TEXT_HIGH)
PICTURE_RECT = pygame.Rect(LISTS_START_X_OFFSET + 2*BUTTON_WIDTH + 2*SPACING, BKG_SELECTED_LIST_Y + 255, 2*LISTS_WIDTH + 2*LISTS_OFFSET, BUTTONS_COLUMN_HEIGHT)


# TMVA usage
SELECTED_DISCRIMINATORS_RECT = pygame.Rect(LISTS_START_X_OFFSET, 80,LISTS_WIDTH, TEXT_HIGH)
SELECT_BKG_RECT2 = pygame.Rect(LISTS_START_X_OFFSET, 80 ,LISTS_WIDTH, TEXT_HIGH)

#ENTER
USERNAME_RECT = pygame.Rect(WIDTH // 2 - 200, HEIGHT // 2 - 100, 400, 40)
PSWD_RECT = pygame.Rect(WIDTH // 2 - 200, HEIGHT // 2 + 20, 400, 40)

#PROJECT
PROJ_NAME_RECT = pygame.Rect(WIDTH // 2 - 200, HEIGHT // 2 - 100, 400, 40)
END_STATE_RECT = pygame.Rect(WIDTH // 2 - 200, HEIGHT // 2 + 20, 400, 40)







