
WIDTH, HEIGHT = 2000, 1400

LISTS_WIDTH = 400
LISTS_HEIGHT = HEIGHT//2 - 100
LISTS_OFFSET = 60
LISTS_START_X_OFFSET = 30
LISTS_START_Y_OFFSET = 150
TEXT_HIGH = 60
TEXT_OFFSET_INSIDE_LIST = 20
#BUTTON_Y_OFFSET =  (PUMPING_INFO_RECT.bottom) + LISTS_OFFSET

BUTTON_Y_OFFSET =  (LISTS_START_Y_OFFSET + LISTS_HEIGHT + LISTS_OFFSET + 250) + LISTS_OFFSET
BUTTON_WIDTH = 400
BUTTON_HEIGHT = 60
SPACING = 10

REDUCE_LISTS_WIDTH = 200
PICTURE_HEIGHT = 300
PICTURE_WIDTH = 700

# DATA AND MC TAB
PUMPING_LIST_POSITION = WIDTH//2 - 3*LISTS_WIDTH//2 - LISTS_OFFSET
MODELING_LIST_POSITION = WIDTH//2 - LISTS_WIDTH//2
NTIPLE_VARS_LIST_POSITION = WIDTH//2 + LISTS_WIDTH//2 + LISTS_OFFSET

# SELECTIONS TAB


# TMVA TAB


# TMVA RESULTS TAB
MAX_BUTTONS_PER_COLUMN = (LISTS_HEIGHT + LISTS_OFFSET) // (BUTTON_HEIGHT + SPACING)
BUTTONS_COLUMN_HEIGHT = MAX_BUTTONS_PER_COLUMN * (BUTTON_HEIGHT + SPACING) - SPACING

BKG_SELECTED_LIST_X = LISTS_START_X_OFFSET
BKG_SELECTED_LIST_Y = 80 + TEXT_HIGH

# TMVA USAGE


# EXISTING DATA AND MC
# sizes for input boxes
TEXT_RECT_HEIGHT = 80
INPUT_HEIGHT = 50
DISTANCE_BETWEEN_X = 0.05 * LISTS_WIDTH
DISTANCE_BETWEEN_Y = 20
VAR_INPUT_WIDTH = 0.4*LISTS_WIDTH
FILENAME_INPUT_WIDTH = LISTS_WIDTH
PATH_INPUT_WIDTH = 2.5*LISTS_WIDTH
START_INPUT_X = WIDTH//2 - 2*LISTS_WIDTH
START_INPUT_Y = 80 + 200 + TEXT_RECT_HEIGHT + 2*DISTANCE_BETWEEN_Y

SIGNAL_INPUT_START_Y = START_INPUT_Y + INPUT_HEIGHT + 2*DISTANCE_BETWEEN_Y
BACKGROUND_INPUT_START_Y = START_INPUT_Y + 2*INPUT_HEIGHT + 4*DISTANCE_BETWEEN_Y
PUMPINGS_LIST_START_Y = BACKGROUND_INPUT_START_Y + INPUT_HEIGHT + 3*DISTANCE_BETWEEN_Y + 2*TEXT_RECT_HEIGHT

